name: Fetch CBS data and commit if changed

on:
  schedule:
    - cron: '0 6 * * *' # Schedule it to run every day at 6 AM UTC
  workflow_dispatch:

jobs:
  check-commit-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout with full history

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Run npm run fetch-data
      run: npm run fetch-data

    - name: Check for Uncommitted Changes
      run: |
        if git diff --exit-code -- public/datasets/dashboard_datasets.json; then
          echo "No changes in public/datasets/dashboard_datasets.json"
        else
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add public/datasets/dashboard_datasets.json
          git commit -m "Auto commit: Update data"
          git push origin master
        fi
