name: Fetch latest data

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and commit changes
      run: |
        npm run fetch-data
        git add .
        git diff --cached --exit-code || git commit -m "Fetch latest data from CBS"

    - name: Check for changes
      id: changes
      run: echo "::set-output name=has_changes::$(git diff --name-only HEAD~1 HEAD)"

    - name: Do something with changes
      if: steps.changes.outputs.has_changes != ''
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "githubaction@ravk.nl"
        git push

    - name: Do something without changes
      if: steps.changes.outputs.has_changes == ''
      run: echo "No changes detected"
